version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django-aws-ec2-autoscaling
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runsas: root
  
  BeforeInstall:
    - location: scripts/instance_os_dependencies.sh
    - location: scripts/python_dependencies.sh
    
      timeout: 300
      runsas: root
  
  AfterInstall:
    - location: scripts/after_install.sh
    - location: scripts/gunicorn.sh
      timeout: 300
      runsas: root
  
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runsas: root


